package com.taskpulse.api.task;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.LinkedHashSet;
import java.util.Set;

import org.hibernate.annotations.BatchSize;

import com.taskpulse.api.tag.Tag;
import com.taskpulse.api.user.User;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;

/**
 * A single task, owned by exactly one {@link User}.
 *
 * <p>This entity is the source of truth for the {@code tasks} table: the schema is
 * generated by Hibernate ({@code ddl-auto=update}), so the column metadata below must
 * stay in sync with the agreed table definition.</p>
 *
 * <h2>Derived columns</h2>
 * Four columns are maintained by this class rather than written by callers, and the
 * setters below are the only place that may change them:
 * <ul>
 *   <li>{@code completed} mirrors {@code status == DONE}. It predates the kanban workflow
 *       and is kept so the original API field and toggle endpoint still mean something.</li>
 *   <li>{@code completed_at} records <em>when</em> a task reached DONE, which the dashboard
 *       needs to plot a completion trend; {@code updated_at} cannot answer that.</li>
 *   <li>{@code priority_weight} is the numeric rank behind {@link TaskPriority}, so the
 *       database can order by urgency instead of alphabetically.</li>
 *   <li>{@code status_weight} does the same for {@link TaskStatus}. Both enums are stored
 *       as strings, and sorting those alphabetically gives HIGH before LOW, and DONE before
 *       TODO — rankings that look plausible and are wrong.</li>
 * </ul>
 *
 * <p>Hibernate uses field access for this entity (the identifier is annotated on a field),
 * so loading a row does not run the setters and cannot disturb a stored value.</p>
 *
 * <h2>Columns added to an existing table</h2>
 * The new non-nullable columns declare a {@code columnDefinition} carrying a SQL default.
 * That is what lets {@code ddl-auto=update} add them to a table which already has rows,
 * instead of failing on the NOT NULL constraint. {@code owner_id} has no sensible default,
 * so it stays nullable in the database and is enforced in the service layer;
 * {@code TaskDataInitializer} adopts any pre-existing row on first start.
 */
@Entity
@Table(name = "tasks", indexes = {
		@Index(name = "ix_tasks_owner", columnList = "owner_id"),
		@Index(name = "ix_tasks_owner_status", columnList = "owner_id, status"),
		@Index(name = "ix_tasks_owner_board", columnList = "owner_id, status_weight, position"),
		@Index(name = "ix_tasks_owner_due_date", columnList = "owner_id, due_date")
})
public class Task {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", nullable = false, updatable = false)
	private Long id;

	@Column(name = "title", length = 200, nullable = false)
	private String title;

	@Column(name = "description", columnDefinition = "TEXT")
	private String description;

	@Column(name = "due_date")
	private LocalDate dueDate;

	@Enumerated(EnumType.STRING)
	@Column(name = "status", length = 20, nullable = false, columnDefinition = "varchar(20) default 'TODO'")
	private TaskStatus status = TaskStatus.TODO;

	@Enumerated(EnumType.STRING)
	@Column(name = "priority", length = 20, nullable = false, columnDefinition = "varchar(20) default 'MEDIUM'")
	private TaskPriority priority = TaskPriority.MEDIUM;

	/** Derived from {@link #priority}; see the class notes on derived columns. */
	@Column(name = "priority_weight", nullable = false, columnDefinition = "integer default 2")
	private int priorityWeight = TaskPriority.MEDIUM.getWeight();

	/** Derived from {@link #status}; see the class notes on derived columns. */
	@Column(name = "status_weight", nullable = false, columnDefinition = "integer default 1")
	private int statusWeight = TaskStatus.TODO.getWeight();

	/** Rank of this task inside its board column. Contiguous from 0 after any board move. */
	@Column(name = "position", nullable = false, columnDefinition = "integer default 0")
	private int position;

	/** Derived from {@link #status}; see the class notes on derived columns. */
	@Column(name = "completed", nullable = false)
	private boolean completed = false;

	/** Derived from {@link #status}; see the class notes on derived columns. */
	@Column(name = "completed_at")
	private LocalDateTime completedAt;

	/**
	 * Owning account. Required by the application, but declared nullable here on purpose:
	 * {@code optional = false} would make Hibernate generate the column as NOT NULL, and
	 * {@code ddl-auto=update} cannot add a NOT NULL column without a default to a table
	 * that already has rows — the ALTER fails and the column never appears. The service
	 * layer always sets an owner, and {@code TaskDataInitializer} adopts any row that
	 * predates accounts.
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "owner_id", nullable = true)
	private User owner;

	/**
	 * Labels on this task. Batch-fetched rather than join-fetched: a join fetch of a
	 * collection cannot be combined with SQL-level pagination, and Hibernate would quietly
	 * fall back to paging the whole result set in memory. With a batch size, one page of
	 * tasks costs one extra query instead of one per row.
	 */
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "task_tags",
			joinColumns = @JoinColumn(name = "task_id"),
			inverseJoinColumns = @JoinColumn(name = "tag_id"),
			indexes = @Index(name = "ix_task_tags_tag", columnList = "tag_id"))
	@BatchSize(size = 32)
	private Set<Tag> tags = new LinkedHashSet<>();

	@Column(name = "created_at", nullable = false, updatable = false)
	private LocalDateTime createdAt;

	@Column(name = "updated_at", nullable = false)
	private LocalDateTime updatedAt;

	public Task() {
	}

	@PrePersist
	protected void onCreate() {
		LocalDateTime now = LocalDateTime.now();
		this.createdAt = now;
		this.updatedAt = now;
	}

	@PreUpdate
	protected void onUpdate() {
		this.updatedAt = LocalDateTime.now();
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public LocalDate getDueDate() {
		return dueDate;
	}

	public void setDueDate(LocalDate dueDate) {
		this.dueDate = dueDate;
	}

	public TaskStatus getStatus() {
		return status;
	}

	/**
	 * Moves the task to a workflow status and brings the two derived completion columns
	 * with it. A task that is already finished keeps its original {@code completedAt}, so
	 * re-saving a DONE task does not rewrite history; reopening one clears it.
	 */
	public void setStatus(TaskStatus status) {
		this.status = status != null ? status : TaskStatus.TODO;
		this.statusWeight = this.status.getWeight();
		this.completed = this.status.isDone();
		if (this.completed) {
			if (this.completedAt == null) {
				this.completedAt = LocalDateTime.now();
			}
		}
		else {
			this.completedAt = null;
		}
	}

	public TaskPriority getPriority() {
		return priority;
	}

	public void setPriority(TaskPriority priority) {
		this.priority = priority != null ? priority : TaskPriority.MEDIUM;
		this.priorityWeight = this.priority.getWeight();
	}

	public int getPriorityWeight() {
		return priorityWeight;
	}

	public int getStatusWeight() {
		return statusWeight;
	}

	public int getPosition() {
		return position;
	}

	public void setPosition(int position) {
		this.position = position;
	}

	public boolean isCompleted() {
		return completed;
	}

	/**
	 * Convenience for the toggle endpoint and the original {@code completed} API field.
	 * Completing a task sends it to DONE; reopening one sends it back to TODO, since a
	 * boolean cannot say whether the task had been in progress before.
	 */
	public void setCompleted(boolean completed) {
		setStatus(completed ? TaskStatus.DONE : TaskStatus.TODO);
	}

	public LocalDateTime getCompletedAt() {
		return completedAt;
	}

	public User getOwner() {
		return owner;
	}

	public void setOwner(User owner) {
		this.owner = owner;
	}

	public Set<Tag> getTags() {
		return tags;
	}

	/** Replaces the label set in place, so Hibernate keeps tracking the same collection. */
	public void setTags(Set<Tag> tags) {
		this.tags.clear();
		if (tags != null) {
			this.tags.addAll(tags);
		}
	}

	public void removeTag(Tag tag) {
		this.tags.remove(tag);
	}

	public LocalDateTime getCreatedAt() {
		return createdAt;
	}

	public void setCreatedAt(LocalDateTime createdAt) {
		this.createdAt = createdAt;
	}

	public LocalDateTime getUpdatedAt() {
		return updatedAt;
	}

	public void setUpdatedAt(LocalDateTime updatedAt) {
		this.updatedAt = updatedAt;
	}
}
